swagger: '2.0'
info:
  title: backend_nodejs_restify_waterline_typescript API
  description: REST API backend written on Node.JS in TypeScript with restify and waterline
  version: "0.0.0"

schemes:
  - http
  - https

basePath: /api
produces:
  - application/json
paths:
  /user:
    get:
      summary: Retrieve user data
      security:
      - X-Access-Token: []
      responses:
        200:
          description: User associated with that access token
          schema:
            $ref: '#/definitions/User'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      summary: Create user
      parameters:
        - name: user
          in: body
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        201:
          description: Created user
          schema:
            $ref: '#/definitions/User'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    put:
      summary: Update user
      security:
      - X-Access-Token: []
      parameters:
        - name: user
          in: body
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        200:
          description: Updated user
          schema:
            $ref: '#/definitions/User'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    delete:
      summary: Delete user
      security:
      - X-Access-Token: []
      responses:
        204:
          description: User associated with that access token
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /auth:
    post:
      summary: Login user
      parameters:
        - name: user
          in: body
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        201:
          description: Created user
          schema:
            $ref: '#/definitions/Token'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    delete:
      summary: Logout user
      security:
      - X-Access-Token: []
      responses:
        204:
          description: User associated with that access token
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  User:
    type: object
    properties:
      email:
        type: string
      password:
        type: string
      title:
        type: string
      updatedAt:
        format: date-time
      createdAt:
        format: date-time
    required:
      - email
      - password
  Token:
    type: object
    properties:
       access_token:
         type: string
    required:
      - access_token
  Error:
    type: object
    properties:
      error:
        type: string
      error_message:
        type: string
securityDefinitions:
  X-Access-Token:
    type: apiKey
    name: X-Access-Token
    in: header
    description: Valid Access Token from which user can be found at
